### ISSUE TITLE
Kevin: Would we ever have to replace a Target Spend file?

### ISSUE THREAD

**Issue by crgarno** [LogicSource/SpendTrack#11]
If the answer is 'Yes', then we should consider duplicating a lot of data into Tracker, or something else.

**Comment by chetan-jadhav** [comment]
@crgarno, so here we will not allow to update values from "target_spends" table but analysts can update values from "trackings" table which are spends value, savings value and taxonomy. Please correct me if I am wrong here.

**Comment by crgarno** [comment]
@chetan-jadhav Correct; the Target Spend that we upload will be locked from editing. I added a story (I think) to the backlog that at some point we will allow a tightly controlled feature to be able to 'replace' the target spend. but not now. For now, we upload target spend, lock it, copy it to what we call tracker data which is where all of the CRUD goes.
