### ISSUE TITLE
Fix text on several pages

### ISSUE THREAD

**Issue by crgarno** [LogicSource/SpendTrack#114]
Wave Detail page: 'Upload target spend' and 'Upload ramp' buttons should be 'Upload Target Spend' and 'Upload Ramp' respectively.

Target Spend table: 'Level1', 'Level2', 'Level3' should be 'Level 1', 'Level 2', 'Level 3' respectively.

Tracker Table: 'Explaination of Missing Savings' should be 'Explanation of Missing Savings'
Tracker Table: 'Saving Validation Comments' should be 'Savings Validation Comments'

**Comment by smita7875** [comment]
Please verify this change

**Comment by crgarno** [comment]
Verified
