### ISSUE TITLE
Add/Change icons in Navigation bar and drop down menu lists

### ISSUE THREAD

**Issue by crgarno** [LogicSource/SpendTrack#93]
Add/Change the following icons to the drop down menu choices:

From the Atlant Icons library.
The icons should have the same hover color (orange) as the other choices in the navigation bar

Waves: Add icon fa-files-o
Projects: Add icon fa-calendar
Spend: Add icon fa-usd

Admin: Change to fa-cogs
Profile: Change to fa-user
Logout: Change to fa-sign-out
Clients: Change to fa-smile-o
Suppliers: Change to fa-truck
Taxonomy: Change to fa-sitemap
Statuses: Change to fa-tasks
Tasks: Change to fa-briefcase

**Comment by smita7875** [comment]
This is done
