### ISSUE TITLE
Change Vendor Number and Vendor Name to Supplier

### ISSUE THREAD

**Issue by crgarno** [LogicSource/SpendTrack#94]
The Target Spend Upload Template uses the term 'Vendor' and it should be 'Supplier'.

Craig changed the xlsx upload template in SharePoint to 'Supplier Number' and 'Supplier Name'.
We need to change column labels in the Target Spend tab in the Wave Detail from 'Vendor Number' and 'Vendor Name' to 'Supplier Number' and 'Supplier Name' respectively.

In SpendTrack we should always be using the term Supplier and not Vendor.

**Comment by smita7875** [comment]
This is done

**Comment by crgarno** [comment]
Verified
